// paguro-api.json -> C# (INTERFACES.md §11.7: "Rust types and C# types both
// generated from it"). Usage: Paguro.Api.Codegen <schema.json> <out.cs>
//
// - every $defs entry becomes a class; `CommonParams` becomes the abstract
//   `ParamsBase` every *Params class derives from;
// - JSON names stay snake_case on the wire ([JsonPropertyName]), properties
//   are PascalCase; optional or null-able fields are nullable;
// - data classes keep unknown fields ([JsonExtensionData]): the API adds
//   fields without a version bump;
// - `PaguroMethods` has one constant per method and the method table;
//   `PaguroCalls` one typed extension method per method on IPaguroClient.
using System.Text;
using System.Text.Json;

if (args.Length != 2)
{
    Console.Error.WriteLine("usage: Paguro.Api.Codegen <paguro-api.json> <out.cs>");
    return 2;
}
using var doc = JsonDocument.Parse(File.ReadAllText(args[0]));
var root = doc.RootElement;
var defs = root.GetProperty("$defs");
var methods = root.GetProperty("methods");
var paramDefs = new HashSet<string>();
foreach (var m in methods.EnumerateObject())
    paramDefs.Add(RefName(m.Value.GetProperty("params")));

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated> from windows/api/paguro-api.json by Paguro.Api.Codegen. Do not edit. </auto-generated>");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine("using System.Text.Json;");
sb.AppendLine("using System.Text.Json.Nodes;");
sb.AppendLine("using System.Text.Json.Serialization;");
sb.AppendLine("using System.Threading;");
sb.AppendLine("using System.Threading.Tasks;");
sb.AppendLine();
sb.AppendLine("namespace Paguro.Api;");
sb.AppendLine();

foreach (var d in defs.EnumerateObject())
{
    var name = d.Name == "CommonParams" ? "ParamsBase" : d.Name;
    var isParams = paramDefs.Contains(d.Name);
    var isBase = d.Name == "CommonParams";
    Doc(sb, d.Value, "");
    var kw = isBase ? "public abstract partial class" : "public sealed partial class";
    var inherit = isParams ? " : ParamsBase" : "";
    sb.AppendLine($"{kw} {name}{inherit}");
    sb.AppendLine("{");
    var required = new HashSet<string>();
    if (d.Value.TryGetProperty("required", out var req))
        foreach (var r in req.EnumerateArray()) required.Add(r.GetString()!);
    if (d.Value.TryGetProperty("properties", out var props))
    {
        foreach (var p in props.EnumerateObject())
        {
            var (type, nullable) = TypeOf(p.Value);
            // Parameters: anything not required is optional and omitted when unset.
            var optional = !required.Contains(p.Name) || nullable;
            var t = optional && !type.EndsWith("?") ? type + "?" : type;
            Doc(sb, p.Value, "    ");
            sb.AppendLine($"    [JsonPropertyName(\"{p.Name}\")]");
            if (optional && (isParams || isBase))
                sb.AppendLine("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
            var init = !optional && type.StartsWith("List<") ? " = new();" : !optional && type == "string" ? " = \"\";" : "";
            if (!optional && !type.StartsWith("List<") && type != "string" && IsClass(type))
                init = " = new();";
            var member = Pascal(p.Name);
            if (member == name) member = type.StartsWith("List<") ? "Items" : "Value";
            sb.AppendLine($"    public {t} {member} {{ get; set; }}{init}");
        }
    }
    if (!isParams && !isBase)
    {
        sb.AppendLine("    /// <summary>Fields this version of the schema does not name.</summary>");
        sb.AppendLine("    [JsonExtensionData]");
        sb.AppendLine("    public Dictionary<string, JsonElement>? Extra { get; set; }");
    }
    sb.AppendLine("}");
    sb.AppendLine();
}

sb.AppendLine("/// <summary>A method of the API: its access, CLI command and cmdlets.</summary>");
sb.AppendLine("public sealed record PaguroMethodInfo(string Name, string Access, string Cli, IReadOnlyList<string> CliExample, IReadOnlyList<string> Cmdlets, System.Type Params, System.Type Result, bool Progress, string? Stub, IReadOnlyList<string> Gated, bool DryRunRead);");
sb.AppendLine();
sb.AppendLine("public static partial class PaguroMethods");
sb.AppendLine("{");
sb.AppendLine($"    public const string ApiVersion = \"{root.GetProperty("version").GetString()}\";");
foreach (var m in methods.EnumerateObject())
    sb.AppendLine($"    public const string {MethodIdent(m.Name)} = \"{m.Name}\";");
sb.AppendLine("    public static readonly IReadOnlyList<PaguroMethodInfo> All = new PaguroMethodInfo[]");
sb.AppendLine("    {");
foreach (var m in methods.EnumerateObject())
{
    var v = m.Value;
    string Strs(string prop) => v.TryGetProperty(prop, out var a)
        ? "new[] { " + string.Join(", ", a.EnumerateArray().Select(x => Lit(x.GetString()!))) + " }"
        : "System.Array.Empty<string>()";
    var stub = v.TryGetProperty("stub", out var s) ? Lit(s.GetString()!) : "null";
    var progress = v.TryGetProperty("progress", out var pr) && pr.GetBoolean() ? "true" : "false";
    var dry = v.TryGetProperty("dry_run_read", out var dr) && dr.GetBoolean() ? "true" : "false";
    var pName = ClassOf(RefName(v.GetProperty("params")));
    var rName = ClassOf(RefName(v.GetProperty("result")));
    sb.AppendLine($"        new PaguroMethodInfo({Lit(m.Name)}, {Lit(v.GetProperty("access").GetString()!)}, {Lit(v.GetProperty("cli").GetString()!)}, {Strs("cli_example")}, {Strs("cmdlets")}, typeof({pName}), typeof({rName}), {progress}, {stub}, {Strs("gated")}, {dry}),");
}
sb.AppendLine("    };");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("/// <summary>One typed call per method.</summary>");
sb.AppendLine("public static partial class PaguroCalls");
sb.AppendLine("{");
foreach (var m in methods.EnumerateObject())
{
    var v = m.Value;
    var pName = ClassOf(RefName(v.GetProperty("params")));
    var rName = ClassOf(RefName(v.GetProperty("result")));
    sb.AppendLine($"    /// <summary>{Xml(v.GetProperty("summary").GetString()!)} (<c>{m.Name}</c>, {v.GetProperty("access").GetString()})</summary>");
    sb.AppendLine($"    public static Task<PaguroResult<{rName}>> {MethodIdent(m.Name)}Async(this IPaguroClient client, {pName}? parameters = null, System.IProgress<Progress>? progress = null, CancellationToken cancel = default)");
    sb.AppendLine($"        => client.CallAsync<{rName}>({Lit(m.Name)}, parameters ?? new {pName}(), progress, cancel);");
}
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
var text = sb.ToString().Replace("\r\n", "\n");
if (!File.Exists(args[1]) || File.ReadAllText(args[1]) != text)
    File.WriteAllText(args[1], text);
return 0;

static string RefName(JsonElement e) => e.GetProperty("$ref").GetString()!.Replace("#/$defs/", "");
static string ClassOf(string def) => def == "CommonParams" ? "ParamsBase" : def;
static bool IsClass(string t) => !(t is "string" or "bool" or "long" or "ulong" or "double" or "JsonNode");

static (string Type, bool Nullable) TypeOf(JsonElement s)
{
    if (s.TryGetProperty("$ref", out _)) return (ClassOf(RefName(s)), false);
    if (s.TryGetProperty("anyOf", out var any))
    {
        var branches = any.EnumerateArray().ToList();
        var nonNull = branches.Where(b => !(b.TryGetProperty("type", out var t) && t.ValueKind == JsonValueKind.String && t.GetString() == "null")).ToList();
        if (nonNull.Count == 1) return (TypeOf(nonNull[0]).Type, branches.Count > 1);
        return ("JsonNode", true);
    }
    if (!s.TryGetProperty("type", out var type)) return ("JsonNode", true);
    var nullable = false;
    string? t0;
    if (type.ValueKind == JsonValueKind.Array)
    {
        var ts = type.EnumerateArray().Select(x => x.GetString()!).ToList();
        nullable = ts.Contains("null");
        t0 = ts.FirstOrDefault(x => x != "null");
    }
    else t0 = type.GetString();
    var format = s.TryGetProperty("format", out var f) ? f.GetString() : null;
    var cs = t0 switch
    {
        "string" => "string",
        "boolean" => "bool",
        "integer" => format == "uint64" ? "ulong" : "long",
        "number" => "double",
        "array" => $"List<{Elem(s)}>",
        "object" => "JsonNode",
        _ => "JsonNode",
    };
    return (cs, nullable);
}

static string Elem(JsonElement s)
{
    if (!s.TryGetProperty("items", out var it)) return "JsonNode";
    var (t, n) = TypeOf(it);
    return n && !t.EndsWith("?") ? t + "?" : t;
}

static string Pascal(string snake)
{
    var parts = snake.Split('_', '-', '.');
    var s = string.Concat(parts.Where(p => p.Length > 0).Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
    return s == "Extra" ? "ExtraField" : s;
}

static string MethodIdent(string m) => Pascal(m.Replace('.', '_').Replace('-', '_'));

static string Lit(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
static string Xml(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

static void Doc(StringBuilder sb, JsonElement s, string indent)
{
    if (s.TryGetProperty("description", out var d) && d.GetString() is { Length: > 0 } text)
        sb.AppendLine($"{indent}/// <summary>{Xml(text)}</summary>");
}
