#!/usr/bin/env python3
"""Draw themes/default/images/logo.png: a small hermit crab in a spiral shell.

Pure Python (standard library only) and deterministic, so the committed PNG
can be regenerated byte for byte:

    python3 themes/tools/draw-logo.py [OUT.png] [--palette default|contrast|light]

`light` is the same crab, a shade deeper, for light backgrounds
(themes/default/images/logo-light.png).

Shapes are signed-distance functions; each pixel's coverage is the distance
to the shape's edge clamped to [0, 1] (one-pixel anti-aliasing), composited
back to front with straight alpha. build.rs premultiplies and scales it to
the sizes the theme asks for.
"""

import math
import struct
import sys
import zlib

SIZE = 256

PALETTES = {
    # shell, spiral, body, claw, eye white, pupil
    "default": ((0xE8, 0x87, 0x5B), (0xA9, 0x4E, 0x2E), (0xF3, 0xC1, 0x9B),
                (0xEC, 0xA0, 0x74), (0xFF, 0xFF, 0xFF), (0x16, 0x19, 0x1F)),
    "contrast": ((0xFF, 0xA0, 0x40), (0x60, 0x28, 0x00), (0xFF, 0xE0, 0xB0),
                 (0xFF, 0xC0, 0x70), (0xFF, 0xFF, 0xFF), (0x00, 0x00, 0x00)),
    "light": ((0xD8, 0x6C, 0x3C), (0x8C, 0x3A, 0x1A), (0xE0, 0xA0, 0x74),
              (0xD4, 0x80, 0x52), (0xFF, 0xFF, 0xFF), (0x16, 0x19, 0x1F)),
}


def circle(cx, cy, r):
    return (lambda x, y: math.hypot(x - cx, y - cy) - r), (cx - r, cy - r, cx + r, cy + r)


def ellipse(cx, cy, rx, ry):
    # Scaled-circle approximation: exact on the axes, close enough elsewhere
    # for a one-pixel anti-aliased edge.
    k = min(rx, ry)

    def d(x, y):
        return (math.hypot((x - cx) / rx, (y - cy) / ry) - 1.0) * k

    return d, (cx - rx, cy - ry, cx + rx, cy + ry)


def capsule(ax, ay, bx, by, r):
    dx, dy = bx - ax, by - ay
    ll = dx * dx + dy * dy

    def d(x, y):
        t = 0.0 if ll == 0 else max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / ll))
        return math.hypot(x - ax - t * dx, y - ay - t * dy) - r

    return d, (min(ax, bx) - r, min(ay, by) - r, max(ax, bx) + r, max(ay, by) + r)


def wedge(ax, ay, direction, half):
    """The infinite V with its apex at (ax, ay), opening towards `direction`
    (radians) with half-angle `half`."""
    n1 = (math.cos(direction + half + math.pi / 2), math.sin(direction + half + math.pi / 2))
    n2 = (math.cos(direction - half - math.pi / 2), math.sin(direction - half - math.pi / 2))

    def d(x, y):
        px, py = x - ax, y - ay
        return max(px * n1[0] + py * n1[1], px * n2[0] + py * n2[1])

    return d, (-1e9, -1e9, 1e9, 1e9)


def cut(a, b):
    """`a` without `b`."""
    fa, fb = a[0], b[0]
    return (lambda x, y: max(fa(x, y), -fb(x, y))), a[1]


def union(*shapes):
    fs = [s[0] for s in shapes]
    boxes = [s[1] for s in shapes]

    def d(x, y):
        return min(f(x, y) for f in fs)

    box = (min(b[0] for b in boxes), min(b[1] for b in boxes),
           max(b[2] for b in boxes), max(b[3] for b in boxes))
    return d, box


def spiral(cx, cy, r0, r1, turns, width, start):
    pts = []
    n = 90
    for i in range(n + 1):
        t = i / n
        th = start + t * turns * 2 * math.pi
        r = r0 + (r1 - r0) * t
        pts.append((cx + r * math.cos(th), cy + r * math.sin(th)))
    return union(*[capsule(*pts[i], *pts[i + 1], width / 2) for i in range(n)])


def scene(pal):
    shell, groove, body, claw, white, pupil = pal
    sx, sy = 152, 112
    layers = []
    # Legs first, under the body.
    legs = union(
        capsule(84, 196, 70, 230, 5.5),
        capsule(104, 200, 102, 236, 5.5),
        capsule(124, 196, 136, 228, 5.5),
    )
    layers.append((legs, body))
    # The shell: a round whorl with its opening towards the lower left.
    layers.append((ellipse(sx, sy, 88, 82), shell))
    layers.append((spiral(sx + 4, sy - 2, 6, 66, 2.25, 11, 0.9), groove))
    # The body emerging from the opening.
    layers.append((ellipse(100, 178, 52, 30), body))
    # Eye stalks and eyes.
    layers.append((union(capsule(84, 160, 70, 112, 4.5), capsule(106, 158, 110, 108, 4.5)), body))
    layers.append((union(circle(68, 104, 13), circle(111, 100, 13)), white))
    layers.append((union(circle(65, 105, 6), circle(108, 101, 6)), pupil))
    # The big claw: a round pincer with a V between its fingers, on a wrist.
    layers.append((capsule(58, 188, 84, 182, 8), claw))
    pincer = cut(ellipse(44, 188, 27, 24), wedge(42, 190, math.pi, 0.36))
    layers.append((pincer, claw))
    return layers


def render(pal):
    rgba = bytearray(SIZE * SIZE * 4)
    for (f, box), (r, g, b) in scene(pal):
        x0, y0 = max(0, int(box[0]) - 2), max(0, int(box[1]) - 2)
        x1, y1 = min(SIZE, int(box[2]) + 3), min(SIZE, int(box[3]) + 3)
        for y in range(y0, y1):
            for x in range(x0, x1):
                cov = 0.5 - f(x + 0.5, y + 0.5)
                if cov <= 0:
                    continue
                a = min(1.0, cov)
                i = (y * SIZE + x) * 4
                da = rgba[i + 3] / 255.0
                oa = a + da * (1 - a)
                for c, v in enumerate((r, g, b)):
                    dc = rgba[i + c]
                    rgba[i + c] = round((v * a + dc * da * (1 - a)) / oa) if oa > 0 else 0
                rgba[i + 3] = round(oa * 255)
    return rgba


def png(rgba):
    raw = b"".join(b"\0" + bytes(rgba[y * SIZE * 4:(y + 1) * SIZE * 4]) for y in range(SIZE))

    def chunk(t, data):
        c = struct.pack(">I", len(data)) + t + data
        return c + struct.pack(">I", zlib.crc32(t + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    pal = "default"
    for name in PALETTES:
        if f"--palette={name}" in sys.argv or (
                "--palette" in sys.argv and sys.argv[sys.argv.index("--palette") + 1] == name):
            pal = name
    args = [a for a in args if a not in PALETTES]
    out = args[0] if args else "themes/default/images/logo.png"
    with open(out, "wb") as f:
        f.write(png(render(PALETTES[pal])))


if __name__ == "__main__":
    main()
