#!/usr/bin/env python3
"""Extract the boot keyboard layouts (INTERFACES.md §13.5) from the X
keyboard configuration database, through libxkbcommon.

    python3 crates/paguro-boot/tools/xkb-keymaps.py

writes, for every layout paguro.ini [UI] keyboard can name:

- crates/paguro-boot/tests/keymaps/<name>.tsv — the reference the table
  tests compare against: one line per physical key and level;
- crates/paguro-boot/src/keymap_tables.rs — the compiled-in tables.

Source: xkeyboard-config (the `symbols/` files: us, gb, de, fr, es, be, ch,
us(intl)), compiled by libxkbcommon with the evdev rules — the data every
Linux desktop types with. The version used is recorded in both outputs.
Dead keys (keysyms without a character) are recorded as absent: the loader
does not compose.
"""

import ctypes
import ctypes.util
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LAYOUTS = [
    # paguro name, xkb layout, xkb variant, display name
    ("us", "us", "", "Us"),
    ("uk", "gb", "", "Uk"),
    ("de", "de", "", "De"),
    ("fr", "fr", "", "Fr"),
    ("es", "es", "", "Es"),
    ("be", "be", "", "Be"),
    ("ch-de", "ch", "", "ChDe"),
    ("nl-intl", "us", "intl", "NlIntl"),
]

# The physical keys US firmware can report, in table order, with their
# evdev keycodes (+8 for xkb). ISO's extra key next to left Shift (LSGT) is
# absent: US firmware reports it as backslash, like BKSL.
KEYS = (
    [("TLDE", 41)]
    + [(f"AE{i:02}", 1 + i) for i in range(1, 13)]
    + [(f"AD{i:02}", 15 + i) for i in range(1, 13)]
    + [("BKSL", 43)]
    + [(f"AC{i:02}", 29 + i) for i in range(1, 12)]
    + [(f"AB{i:02}", 43 + i) for i in range(1, 11)]
)


class RuleNames(ctypes.Structure):
    _fields_ = [(n, ctypes.c_char_p) for n in ("rules", "model", "layout", "variant", "options")]


def main():
    lib = ctypes.CDLL(ctypes.util.find_library("xkbcommon") or "libxkbcommon.so.0")
    lib.xkb_context_new.restype = ctypes.c_void_p
    lib.xkb_keymap_new_from_names.restype = ctypes.c_void_p
    lib.xkb_keymap_new_from_names.argtypes = [ctypes.c_void_p, ctypes.POINTER(RuleNames), ctypes.c_int]
    lib.xkb_keymap_key_get_syms_by_level.argtypes = [
        ctypes.c_void_p, ctypes.c_uint32, ctypes.c_uint32, ctypes.c_uint32,
        ctypes.POINTER(ctypes.POINTER(ctypes.c_uint32))]
    lib.xkb_keysym_to_utf32.restype = ctypes.c_uint32
    lib.xkb_keysym_to_utf32.argtypes = [ctypes.c_uint32]
    ctx = lib.xkb_context_new(0)
    version = subprocess.run(["dpkg-query", "-W", "-f=${Version}", "xkb-data"],
                             capture_output=True, text=True).stdout.strip() or "unknown"
    libver = subprocess.run(["dpkg-query", "-W", "-f=${Version}", "libxkbcommon0"],
                            capture_output=True, text=True).stdout.strip() or "unknown"
    provenance = f"xkeyboard-config {version} (symbols/), libxkbcommon {libver}, evdev rules"

    rust = [
        "// @generated by crates/paguro-boot/tools/xkb-keymaps.py from",
        f"// {provenance}.",
        "// Do not edit: regenerate. '\\0' is a key or level without a character",
        "// (absent, or a dead key).",
        "",
        "use crate::keymap::KEYS;",
        "",
    ]
    for name, layout, variant, ident in LAYOUTS:
        names = RuleNames(b"evdev", b"pc105", layout.encode(), variant.encode(), b"")
        km = lib.xkb_keymap_new_from_names(ctx, ctypes.byref(names), 0)
        assert km, (layout, variant)
        table = []
        for key, code in KEYS:
            levels = []
            for level in range(4):
                syms = ctypes.POINTER(ctypes.c_uint32)()
                n = lib.xkb_keymap_key_get_syms_by_level(km, code + 8, 0, level, ctypes.byref(syms))
                cp = lib.xkb_keysym_to_utf32(syms[0]) if n == 1 else 0
                if cp < 0x20 or cp == 0x7F:
                    cp = 0
                levels.append(cp)
            table.append((key, levels))
        src = f"{layout}({variant})" if variant else layout
        with open(os.path.join(ROOT, "tests", "keymaps", f"{name}.tsv"), "w") as f:
            f.write(f"# {name}: xkb {src}; {provenance}\n")
            f.write("# key\tbase\tshift\taltgr\tshift+altgr (U+hex, - for none)\n")
            for key, lv in table:
                f.write(key + "\t" + "\t".join(f"U+{c:04X}" if c else "-" for c in lv) + "\n")
        rust.append(f"/// `{name}`: xkb `{src}`.")
        rust.append(f"pub static {ident.upper()}: [[char; 4]; KEYS] = [")
        for key, lv in table:
            cells = ", ".join(repr_char(c) for c in lv)
            rust.append(f"    [{cells}], // {key}")
        rust.append("];")
        rust.append("")
    with open(os.path.join(ROOT, "src", "keymap_tables.rs"), "w") as f:
        f.write("\n".join(rust))


def repr_char(cp):
    if cp == 0:
        return "'\\0'"
    c = chr(cp)
    if c == "'":
        return "'\\''"
    if c == "\\":
        return "'\\\\'"
    if cp < 0x7F or c.isprintable():
        return f"'{c}'"
    return f"'\\u{{{cp:x}}}'"


if __name__ == "__main__":
    main()
