[package]
name = "paguro-core"
license.workspace = true
description = "Pure, dependency-free logic shared by paguro-efi, the kernel module and userspace"
edition.workspace = true
version.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dev-dependencies]
proptest = { version = "1", default-features = false, features = ["std"] }
